drop table common_user_follow;
ALTER TABLE common_entity_like drop FOREIGN KEY `user_id_refs_id_99d2be0c`;
alter table common_entity drop FOREIGN KEY `creator_id_refs_id_2c05c85a`;
ALTER TABLE common_entity_note drop FOREIGN KEY  `creator_id_refs_id_973c16b8`;
ALTER TABLE common_note drop FOREIGN KEY `creator_id_refs_id_67e96585`;
ALTER TABLE common_note_comment drop FOREIGN KEY `creator_id_refs_id_aa75a549`;
ALTER TABLE common_note_poke drop FOREIGN KEY `user_id_refs_id_864025aa`;
ALTER TABLE common_note_figure drop FOREIGN KEY `creator_id_refs_id_db9ae3d3`;
ALTER TABLE common_candidate drop FOREIGN KEY `creator_id_refs_id_fc493a35`;
ALTER TABLE common_candidate_note drop FOREIGN KEY `creator_id_refs_id_8fcf5e7f`;
update common_entity set creator_id=79761 where creator_id=1;
update common_entity set creator_id=22045 where creator_id=6;
update common_entity set creator_id=195580 where creator_id=8;
update common_entity_note set creator_id=95064 where creator_id=14;
update common_entity_note set creator_id=79761 where creator_id=1;
update common_entity_note set creator_id=79761 where creator_id=16;
update common_note set creator_id=79761 where creator_id=1;
update common_note set creator_id=95064 where creator_id=14;
update common_note set creator_id=79761 where creator_id=16;
update common_note_figure set creator_id=79761 where creator_id=1;
update common_note_figure set creator_id=95064 where creator_id=14;
update common_note_figure set creator_id=79761 where creator_id=16;
delete from common_note_poke;
